Задачи

    Создать вектор (одномерный массив) размера 10, заполненый нулями
    Создать вектор размер 10, заполненный единицами
    Создать вектор размера 10, заполненный числом 2.5
    Создать вектор заполненный нулями, но пятый элемент равен 1
    Создать вектор со значениями от 10 до 49
    Развернуть вектор (первый становится последним)
    Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
    Найти индексы ненулевых элементов в [1,2,0,0,4,0]
    Создать массив 3x3x3 со случайными значениями
    Создать массив 10x10 со случайными значениями, найти минимум и максимум
    Создать матрицу с 0 внутри и 1 на границах
    Создать матрицу 8x8 и заполнить ее в шахматном порядке
    Перемножить матрицы 5x3 и 3x2
    Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки
    Есть генератор, сделать с его помощью массив

def generate():
    for x in range(10):
            yield x

    Создать двумерный список и преобразовать его в NumPy массив (с типом int32)
    Проверить, одинаковы ли 2 NumPy массива
    Сделать массив неизменяемым


In [1]:
import numpy as np

# 1. создать вектор (одномерный массив) размера 10, заполненный нулями
vector_zeros = np.zeros(10)
print("1. Вектор из нулей:", vector_zeros)

# 2. создать вектор размер 10, заполненный единицами
vector_ones = np.ones(10)
print("2. Вектор из единиц:", vector_ones)

# 3. создать вектор размера 10, заполненный числом 2.5
vector_2_5 = np.full(10, 2.5)
print("3. Вектор из числа 2.5:", vector_2_5)

# 4. создать вектор, заполненный нулями, но пятый элемент равен 1
vector_with_one = np.zeros(10)
vector_with_one[4] = 1
print("4. Вектор с единицей на пятом месте:", vector_with_one)

# 5. создать вектор со значениями от 10 до 49
vector_10_to_49 = np.arange(10, 50)
print("5. Вектор от 10 до 49:", vector_10_to_49)

# 6. развернуть вектор (первый становится последним)
reversed_vector = vector_10_to_49[::-1]
print("6. Развернутый вектор:", reversed_vector)

# 7. создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("7. Матрица 3x3:", matrix_3x3)

# 8. найти индексы ненулевых элементов в [1, 2, 0, 0, 4, 0]
array = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(array)
print("8. Индексы ненулевых элементов:", nonzero_indices)

# 9. создать массив 3x3x3 со случайными значениями
random_3x3x3 = np.random.random((3, 3, 3))
print("9. Массив 3x3x3 со случайными значениями:", random_3x3x3)

# 10. создать массив 10x10 со случайными значениями, найти минимум и максимум
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("10. Массив 10x10 со случайными значениями:\n", random_10x10)
print("    Минимум:", min_val)
print("    Максимум:", max_val)

# 11. создать матрицу с 0 внутри и 1 на границах
matrix_with_ones_border = np.ones((5, 5))
matrix_with_ones_border[1:-1, 1:-1] = 0
print("11. Матрица с нулями внутри и единицами на границе:\n", matrix_with_ones_border)

# 12. создать матрицу 8x8 и заполнить ее в шахматном порядке
chessboard_matrix = np.zeros((8, 8), dtype=int)
chessboard_matrix[1::2, ::2] = 1
chessboard_matrix[::2, 1::2] = 1
print("12. Шахматная матрица 8x8:\n", chessboard_matrix)

# 13. перемножить матрицы 5x3 и 3x2
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print("13. Результат перемножения матриц 5x3 и 3x2:\n", product_matrix)

# 14. создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3, 5] колонки
random_matrix_5x7 = np.random.randint(1, 101, (5, 7))
modified_matrix = np.delete(random_matrix_5x7, [3, 5], axis=1)
print("14. Случайная матрица 5x7 с удалением колонок [3, 5]:\n", modified_matrix)

# 15. есть генератор, сделать с его помощью массив
def generate():
    for x in range(10):
        yield x

generator_array = np.array(list(generate()))
print("15. Массив из генератора:", generator_array)

# 16. создать двумерный список и преобразовать его в NumPy массив (с типом int32)
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_array = np.array(list_2d, dtype=np.int32)
print("16. Двумерный список в NumPy массив:\n", numpy_array)

# 17. проверить, одинаковы ли 2 NumPy массива
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])
arrays_equal = np.array_equal(array1, array2)
print("17. Проверка на одинаковость массивов:", arrays_equal)

# 18. сделать массив неизменяемым
immutable_array = np.array([1, 2, 3, 4])
immutable_array.flags.writeable = False
try:
    immutable_array[0] = 10  # попытка изменить массив вызовет ошибку
except ValueError as e:
    print("18. Попытка изменения неизменяемого массива:", e)


1. Вектор из нулей: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Вектор из единиц: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
3. Вектор из числа 2.5: [2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]
4. Вектор с единицей на пятом месте: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
5. Вектор от 10 до 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
6. Развернутый вектор: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
7. Матрица 3x3: [[0 1 2]
 [3 4 5]
 [6 7 8]]
8. Индексы ненулевых элементов: (array([0, 1, 4]),)
9. Массив 3x3x3 со случайными значениями: [[[0.60785073 0.25506844 0.55414596]
  [0.1863858  0.92664219 0.22754659]
  [0.0329433  0.0893476  0.40860413]]

 [[0.67021596 0.29737531 0.50278806]
  [0.21752398 0.43595816 0.14501984]
  [0.04650503 0.93951254 0.42274747]]

 [[0.88886716 0.07771505 0.41995377]
  [0.31418705 0.2971438  0.04459783]
  [0.5216166  0.7856728  0.781